# argo-workflow-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: openfold
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa          #matches your Helm values
    namespace: openfold
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io