apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfold-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  storageClassName: storageclass-wekafs-dir-api
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: openfold-cache-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 500Gi
#  storageClassName: storageclass-wekafs-dir-api